object(NS_MyRangeException\MyRangeException)#1 (10) {
  ["badValue":"NS_MyRangeException\MyRangeException":private]=>
  int(5)
  ["lowerValue":"NS_MyRangeException\MyRangeException":private]=>
  int(20)
  ["upperValue":"NS_MyRangeException\MyRangeException":private]=>
  int(30)
  ["message":protected]=>
  string(3) "xxx"
  ["string":"Exception":private]=>
  string(0) ""
  ["code":protected]=>
  int(0)
  ["file":protected]=>
  string(%d) "%s/tests/Exception_Handling/MyRangeException_test1.php"
  ["line":protected]=>
  int(8)
  ["trace":"Exception":private]=>
  array(1) {
    [0]=>
    array(4) {
      ["file"]=>
      string(%d) "%s/tests/Exception_Handling/MyRangeException_test1.php"
      ["line"]=>
      int(17)
      ["function"]=>
      string(30) "NS_MyRangeException_test1\main"
      ["args"]=>
      array(0) {
      }
    }
  }
  ["previous":"Exception":private]=>
  NULL
}
=======
$re = >exception 'NS_MyRangeException\MyRangeException' with message 'xxx' in %s/tests/Exception_Handling/MyRangeException_test1.php:8
Stack trace:
#0 %s/tests/Exception_Handling/MyRangeException_test1.php(17): NS_MyRangeException_test1\main()
#1 {main}, badValue: 5, lowerValue: 20, upperValue: 30<
